### ISSUE TITLE
Turns off chat (/say, /raid, /guild)

### ISSUE THREAD

**Issue by yrazu05** [redshadowz/GroupFinder#2]
Hello,
     Great addon, but after update I can't see certain chats in the world. This includes /say, /raid, and /guild. I can't see posts from any of them. Once I turned off the addon, then I was able to once again see other chat options in the world. 

The only chat setting that didn't turn off and was visible was /worldchat. I could still see WorldChat. But I'm not sure why the other chat options are forcibly turned off by the addon.

**Comment by yrazu05** [comment]
Problem still persists after the supposed "fix" if it did happen. Still is shutting down my other chats.

**Comment by redshadowz** [comment]
Could you message me on discord Redshadowz#1594? If you're on the Turtle WoW discord you'll be able to message me directly without adding me as a friend.

I changed a lot with the addon recently but hadn't had the time to test it. I went to my sister's earlier and leveled with my niece and noticed quite a few issues. Basically, my niece couldn't see me typing at all because my friends/group stuff wasn't working right. I'm fairly sure I fixed it. But if you still have the problem with this update, let me know.

BTW: If the recent update fixed the problem, let me know. Thanks.

**Comment by yrazu05** [comment]
I can try to msg you, but as for now the problem still persists. Cant see certain chats except /worldchat. Even after the new update you did. 

Still, great addon, but I have to work around this problem by inviting an alt on another account and have the addon turned off so he could see the chat for me.

**Comment by redshadowz** [comment]
If there are addons that are incompatible with this addon's chat formatting, I could disable chat formatting by default for those addons. Please let me know.

**Comment by redshadowz** [comment]
I figured it out btw. Thanks. It was really simple and stupid.
